### ISSUE TITLE
Issue while logging on Deezer

### ISSUE THREAD

**Issue by YannG91** [ptrk95/MMM-MusicOnDemand#2]
I have an issue "Navigation Timeout Exceeded" when the MMM-MusicOnDemand tries to connect on Deezer. If i set the showBrowser parameter to true in my config.js, i can see that there is a reCAPTCHA that block the logging. Is there a way to get around this reCAPTCHA?

**Comment by ptrk95** [comment]
Oh no that's really bad!
Thank you for pointing that out. 

The only free way I know of is to login in to deezer once and save the login data. I need to change the code for that. Shouldn't take too long.

**Comment by YannG91** [comment]
Great, thanks for the quick reply

**Comment by ptrk95** [comment]
I updated the files. Do a: git pull. And change your config file. Have a look at the updated readme.
