### ISSUE TITLE
showBrowser: true and it works – showBrowser: false and it says initializing... forever 

### ISSUE THREAD

**Issue by lxne** [ptrk95/MMM-MusicOnDemand#6]
Hi, I got it working on my Pi3b+ (buster) only with `showBrowser: true`
if `showBrowser: false` it says _initializing..._ forever.

puppeteer is 1.19.0
chromium is 74.0.3729.157

Any ideas would be welcome.

**Comment by toy31** [comment]
It was same for me too, but when i've changed my rasbian OS, to put STRETCH, and the module is working with magic mirror2. Chromium version: 72.0.3626 / Puppeteer version : 1.11.0.

**Comment by lxne** [comment]
Newly installed RPI 3B+ with Buster and most recent MagicMirror works.
